import type { Metadata } from "next";
import { SectionHeading } from "@/components/custom/SectionHeading";
import { ArrowLeft } from "lucide-react";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms & Conditions - Techpotli Digital",
  description: "Terms and Conditions for Techpotli Digital. Read our terms of use, user responsibilities, and legal obligations.",
  alternates: {
    canonical: "https://www.techpotlidigital.com/terms-conditions",
  },
};

export default function TermsConditionsPage() {
  return (
    <main className="min-h-screen bg-white">
      {/* Hero Section */}
      <section className="relative w-full bg-gradient-to-br from-teal-50 via-cyan-50 to-blue-50 py-16 sm:py-20 md:py-24">
        <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
          <Link
            href="/"
            className="mb-8 inline-flex items-center gap-2 text-gray-600 hover:text-teal-600 transition-colors"
          >
            <ArrowLeft className="h-4 w-4" />
            <span>Back to Home</span>
          </Link>

          <SectionHeading
            badge="Legal Information"
            heading="Terms & Conditions"
            description="Please read these terms carefully before using our platform."
            size="lg"
            align="left"
            as="h1"
            badgeClassName="bg-gradient-to-r from-teal-500 via-cyan-500 to-blue-500 !text-white border-0 shadow-lg"
            showDescriptionToScreenReaders={true}
          />
        </div>
      </section>

      {/* Content Section */}
      <section className="py-12 sm:py-16 md:py-20">
        <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
          <div className="prose prose-lg max-w-none text-gray-700 leading-relaxed space-y-8">
            <div className="bg-yellow-50 border-l-4 border-yellow-400 p-4 mb-8">
              <p className="text-sm text-gray-700">
                <strong>Last Updated:</strong> {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
              </p>
            </div>

            <div>
              <p className="text-gray-600 mb-6">
                This document is an electronic record under the Information Technology Act, 2000 and rules made thereunder, including amendments related to electronic records. This electronic record is generated by a computer system and does not bear any physical or digital signatures.
              </p>
              <p className="text-gray-600 mb-6">
                This Terms of Use ("Terms") applies to the website https://www.techpotlidigital.com (the "Website"), including any associated mobile applications or platforms (collectively, the "Platform"), which is owned and operated by Techpotli E commerce Private Limited, a company incorporated under the Companies Act, 1956, with its registered office at C52A, Kalka Ji, New Delhi – 110019 (hereinafter referred to as "Platform owner", "we", "us", or "our").
              </p>
              <p className="text-gray-600 mb-6">
                Your use of the Platform, including all services, tools, and information provided, is governed by these Terms of Use. By accessing, browsing, or using the Platform, you agree to comply with these Terms and all applicable policies incorporated herein. Any conflicting or additional terms proposed by you are expressly rejected and will have no effect.
              </p>
            </div>

            <div>
              <h2 className="text-2xl sm:text-3xl font-bold text-gray-900 mb-4 mt-8">1. Acceptance of Terms</h2>
              <p className="text-gray-600 mb-4">
                By accessing, browsing, or using the Platform, you ("user", "you", or "your") agree to comply with these Terms and all applicable policies incorporated herein. Any conflicting or additional terms proposed by you are expressly rejected and will have no effect.
              </p>
              <p className="text-gray-600 mb-4">
                Your use of the Platform constitutes a binding legal contract between you and the Platform owner. You are responsible for ensuring that all information you provide during registration and while using the Platform is accurate, complete, and current. You are also responsible for all activities carried out under your account.
              </p>
            </div>

            <div>
              <h2 className="text-2xl sm:text-3xl font-bold text-gray-900 mb-4 mt-8">2. Use of Information and Services</h2>
              <p className="text-gray-600 mb-4">
                The Platform and all services offered are provided "as-is" without warranties or guarantees of any kind, either expressed or implied. While we try to provide accurate, complete, and timely data, the Platform may also comprise inaccuracies, errors, or outdated content material. Your use of the Platform and offerings is fully at your own risk, and we disclaim liability for any loss, damage, or issues arising from such use.
              </p>
              <p className="text-gray-600 mb-4">
                You are encouraged to independently assess the suitability of the Platform and Services for your requirements before relying on them.
              </p>
            </div>

            <div>
              <h2 className="text-2xl sm:text-3xl font-bold text-gray-900 mb-4 mt-8">3. Intellectual Property</h2>
              <p className="text-gray-600 mb-4">
                All content, design, layout, graphics, software, text, and other materials on the Platform are proprietary to us and/or licensed to us. You are not permitted to copy, reproduce, distribute, modify, or create derivative works from any part of the Platform without our previous written consent. Unauthorized use of the Platform may result in legal action under applicable laws.
              </p>
            </div>

            <div>
              <h2 className="text-2xl sm:text-3xl font-bold text-gray-900 mb-4 mt-8">4. User Responsibilities</h2>
              <p className="text-gray-600 mb-4">
                As a user of the Platform, you agree to:
              </p>
              <ul className="list-disc list-inside space-y-2 text-gray-600 mb-4 ml-4">
                <li>Use the Platform and Services only for legal purposes and in accordance with these Terms and applicable laws.</li>
                <li>Refrain from any activity that could damage, disable, or impair the Platform.</li>
                <li>Maintain the confidentiality of your account credentials and be responsible for all activities conducted through your account.</li>
                <li>Pay any fees or charges associated with the Services you use.</li>
                <li>Not engage in any unlawful, illegal, or prohibited activity while using the Platform.</li>
              </ul>
            </div>

            <div>
              <h2 className="text-2xl sm:text-3xl font-bold text-gray-900 mb-4 mt-8">5. Third-Party Links</h2>
              <p className="text-gray-600 mb-4">
                The Platform may contain links to third-party websites or resources. These links are provided solely for your convenience and information. Accessing such websites will be governed by their own terms of use, privacy policies, and other applicable rules. We do not endorse or assume responsibility for any content, products, or services provided by third-party websites.
              </p>
            </div>

            <div>
              <h2 className="text-2xl sm:text-3xl font-bold text-gray-900 mb-4 mt-8">6. Transactions and Legal Obligations</h2>
              <p className="text-gray-600 mb-4">
                When you initiate a transaction through the Platform, you enter into a legally binding contract with the Platform owner for the services provided. You acknowledge that your obligations under these Terms are enforceable, and you will comply with all applicable laws while using the Platform.
              </p>
            </div>

            <div>
              <h2 className="text-2xl sm:text-3xl font-bold text-gray-900 mb-4 mt-8">7. Indemnification</h2>
              <p className="text-gray-600 mb-4">
                You agree to indemnify and hold harmless the Platform owner, its affiliates, officers, directors, employees, and agents from any claims, damages, losses, liabilities, costs, or expenses (including reasonable attorney fees) arising from:
              </p>
              <ul className="list-disc list-inside space-y-2 text-gray-600 mb-4 ml-4">
                <li>Your violation of these Terms, policies, or applicable laws.</li>
                <li>Unauthorized use of the Platform.</li>
                <li>Violation of any third-party rights, including intellectual property rights.</li>
              </ul>
            </div>

            <div>
              <h2 className="text-2xl sm:text-3xl font-bold text-gray-900 mb-4 mt-8">8. Limitation of Liability & Force Majeure</h2>
              <p className="text-gray-600 mb-4">
                The Platform owner shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Platform or Services. Additionally, we are not responsible for delays or failures to perform any obligation caused by force majeure events, including natural disasters, government actions, strikes, or other events beyond our reasonable control.
              </p>
            </div>

            <div>
              <h2 className="text-2xl sm:text-3xl font-bold text-gray-900 mb-4 mt-8">9. Governing Law and Jurisdiction</h2>
              <p className="text-gray-600 mb-4">
                These Terms are governed by the laws of India. Any disputes arising out of or relating to these Terms shall be subject to the exclusive jurisdiction of courts in Delhi, India.
              </p>
            </div>

            <div>
              <h2 className="text-2xl sm:text-3xl font-bold text-gray-900 mb-4 mt-8">10. Communication</h2>
              <p className="text-gray-600 mb-4">
                All queries, concerns, or messages regarding these Terms or the use of the Platform should be addressed using the contact information provided on the Website.
              </p>
            </div>

            <div className="bg-blue-50 border-l-4 border-blue-400 p-6 mt-8 rounded-r-lg">
              <p className="text-sm text-gray-700">
                <strong>Note:</strong> These Terms may be modified at any time without previous notice. Users are encouraged to review the Terms periodically to stay informed of updates. Continued use of the Platform constitutes acceptance of the updated Terms.
              </p>
            </div>
          </div>
        </div>
      </section>
    </main>
  );
}

